steps:
  - label: '🔨 filter MD file'
    command: .buildkite/filter-md-script.sh
    key: filter-pr
    if: build.pull_request.base_branch == "main"
    soft_fail:
      - exit_status: '*'

  - label: 'Run pr-validation only if filter check is passed'
  - command: |
      if [ $$(buildkite-agent step get "outcome" --step "filter-pr") == "passed" ]; then
         cat <<- YAML | buildkite-agent pipeline upload
         steps:
           - label: "Trigger Pr-pipeline"
             trigger: "firstproject"
      YAML
      fi
    depends_on: filter-pr
