steps:
  - label: '🔨 Check for MD file'
    command: .buildkite/filter-md-script.sh
    key: filter-md-script
    if: build.pull_request.base_branch == "main"

  - label: ':pipeline:'
    command: .buildkite/trigger-pr-pipeline-script.sh
    depends_on: filter-md-script
    allow_dependency_failure: true
