steps:
  - label: '🔨 Check for MD file'
    command: .buildkite/filter-md-script.sh
    key: filter
    if: build.pull_request.base_branch == "main"
    soft_fail:
      - exit_status: '*'

  - label: ':pipeline:'
    command: .buildkite/trigger-pr-pipeline-script.sh
    depends_on: filter
    allow_dependency_failure: true
